files:
  - source: app/src/main/res/values-*/strings.xml
    translation: app/src/main/res/values/strings.xml
  - source: app/src/main/res/values/strings.xml
    translation: app/src/main/res/values/strings.xml
bundles:
  - 2
  - 4
